---
layout: post
title: "[javascript] SweetAlert2에서 애러 핸들링하기"
description: " "
date: 2023-10-26
tags: [javascript]
comments: true
share: true
---

SweetAlert2는 매우 유용한 팝업창 라이브러리로, 사용자에게 메시지를 보여주거나 선택지를 제공하는 등 다양한 상황에서 사용할 수 있습니다. 하지만 때로는 SweetAlert2에서 발생하는 애러를 핸들링하는 것이 필요할 수 있습니다. 이번 글에서는 SweetAlert2 내부의 애러를 어떻게 처리하는지 알아보겠습니다.

## 애러 핸들링 방법

SweetAlert2에서 애러를 핸들링하는 가장 간단한 방법은 Promise 체이닝을 통해 애러 핸들러를 추가하는 것입니다. `then()` 메서드의 두 번째 매개변수로 애러 핸들러를 전달하면 됩니다.

```javascript
Swal.fire({
  title: '알림',
  text: '안녕하세요!',
}).then((result) => {
  // 정상적으로 실행되었을 경우
}).catch((error) => {
  // 애러가 발생한 경우
});
```

위의 예제에서 `catch()` 메서드를 사용하여 애러를 처리하고 있습니다. 애러 핸들러 내부에서는 애러에 대한 적절한 처리를 수행할 수 있습니다. 예를 들어, 에러 메시지를 출력하거나 특정 작업을 수행할 수 있습니다.

## 커스텀 애러 핸들링

SweetAlert2는 내부에서 발생하는 애러를 항상 `reject()`를 호출하여 Promise를 reject합니다. 이를 활용하여 자체적으로 커스텀 애러 핸들링을 구현할 수 있습니다.

```javascript
function showAlert() {
  return new Promise((resolve, reject) => {
    Swal.fire({
      title: '알림',
      text: '안녕하세요!',
    }).then((result) => {
      // 정상적으로 실행되었을 경우
      resolve(result);
    }).catch((error) => {
      // 애러가 발생한 경우
      reject(new Error('SweetAlert2 애러 발생'));
    });
  });
}

showAlert().then((result) => {
  console.log(result);
}).catch((error) => {
  console.error(error);
});
```

위의 예제에서는 `showAlert()` 함수를 정의하여 SweetAlert2를 실행하는 로직을 감싸고 있습니다. 이 함수는 Promise를 반환하며, `then()`과 `catch()` 메서드를 이용하여 정상적인 결과와 애러를 핸들링할 수 있습니다. 애러 핸들러 내부에서는 `reject()`를 사용하여 애러를 전달하고 있습니다.

## 참고 자료

- [SweetAlert2 공식 문서](https://sweetalert2.github.io/)
- [JavaScript Promise 체이닝](https://developer.mozilla.org/ko/docs/Web/JavaScript/Guide/Using_promises#%EC%9B%90%EB%A6%AC%ED%95%98%EA%B8%B0_%EC%8B%9C%EC%A0%90%EC%97%90%EC%84%9C_%EB%8A%94_%EC%95%A0%EB%9F%AC)